name: Publish on GitHub

on: [ pull_request, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 17
  VERSION: 1.0.0+1.20.4
  RELEASE_NAME: CookingPowder 1.0.0 for Minecraft 1.20.4

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment
        run: env

      - name: Check Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{env.JAVA_VERSION}}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: "v${{env.VERSION}}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: beta
          changelog-file: CHANGELOG.md
          github-draft: true
          github-prerelease: true